sudo: false
os: linux
language: node_js
node_js: '10'
dist: xenial
cache:
  directories:
    - ~/.nvm
    - ~/.yarn
    - node_modules
    - /home/travis/.cache/Cypress

install:
  - yarn --frozen-lockfile
script:
  - yarn test:unit
  - yarn test:e2e --headless --record --key $CYPRESS_API_KEY
